src/Entity/MyCollection.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\MyCollectionRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: MyCollectionRepository::class)]
class MyCollection
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Assert\Type('integer')]
    #[Groups(['get_collections', 'collection','get_user','get_collection','get_favorite','get_collection_random','get_page_object'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank,Assert\NotNull,Assert\Type('string'),Assert\Length(min: 3, max: 40)]
    #[Groups(['get_collections','collection','get_user','get_collection','get_favorite','get_collection_random','get_page_object'])]
    private ?string $name = null;

    #[ORM\Column(length: 2083)]
    #[Assert\NotBlank,Assert\NotNull,Assert\Image]
    #[Groups(['get_collections','collection','get_user','get_collection','get_favorite','get_collection_random','get_page_object'])]
    private ?string $image = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank,Assert\NotNull,Assert\Length(min: 30, max: 2000),Assert\Type('string')]
    #[Groups(['get_collections','collection','get_collection','get_favorite','get_collection_random','get_page_object'])]
    private ?string $description = null;

    #[ORM\Column(nullable: true,type: Types::DECIMAL, precision: 2, scale: 1)]
    #[Groups(['get_collections','collection','get_collection','get_favorite','get_collection_random','get_page_object'])]
    private ?string $rating = null;

    #[ORM\ManyToOne(inversedBy: 'mycollections')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['get_collections','get_collection','get_page_object'])]
    private ?User $user = null;

    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'myfavoritescollections')]
    private Collection $users;

    #[ORM\ManyToMany(targetEntity: MyObject::class, inversedBy: 'myCollections')]
    #[Groups(['get_collections','get_collection',])]
    private Collection $myobjects;

    #[ORM\Column]
    #[Groups(['get_collections','get_favorite',])]
    #[Assert\Type('datetimeImmutable','get_collection_random')]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    #[Assert\Type('datetimeImmutable','get_collection_random')]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column]
    #[Assert\NotBlank,Assert\NotNull,Assert\Type('bool')]
    private ?bool $is_active = null;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->myobjects = new ArrayCollection();
        $this->created_at = new \DateTimeImmutable();
        $this->updated_at = new \DateTimeImmutable();
        $this->is_active = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }
    
    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getRating(): ?float
    {
        return $this->rating;
    }

    public function setRating(?float $rating): static
    {
        $this->rating = $rating;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addMyFavoriteCollection($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            $user->removeMyFavoriteCollection($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, MyObject>
     */
    public function getMyobjects(): Collection
    {
        return $this->myobjects;
    }

    public function addMyobject(MyObject $myobject): static
    {
        if (!$this->myobjects->contains($myobject)) {
            $this->myobjects->add($myobject);
        }

        return $this;
    }

    public function removeMyobject(MyObject $myobject): static
    {
        $this->myobjects->removeElement($myobject);

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }
}

src/Controller/Api/MyCollectionController.php
<?php

namespace App\Controller\Api;

use App\Entity\MyCollection;
use App\Repository\MyObjectRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\MyCollectionRepository;
use DateTimeImmutable;
use Symfony\Component\Validator\Validation;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

// root URL for all routes from MyCollectionController
#[Route('/api')]
class MyCollectionController extends AbstractController
{
    /**
     * list all collections
     *
     * @param MyCollectionRepository $myCollectionRepository
     * @return Response
     */
    #[Route('/collections', name: 'api_my_collection_list',methods: ['GET'])]
    public function list(MyCollectionRepository $myCollectionRepository): Response
    {
        // retrieve all collections
        $collections = $myCollectionRepository->findAll();
        
        // check if $myCollection doesn't exist
        if (!$collections) {
            return $this->json(
                "Error : Collection inexistante",
                // status code
                404
            );
        }

        // return json
        return $this->json(
            // what I want to show
            $collections,
            // status code
            200,
            // header
            [],
            // groups authorized
            ['groups' => 'get_collections']
        );
    }

    /**
     * list one collection by its id
     *
     * @param MyCollectionRepository $myCollectionRepository
     * @return Response
     */
    #[Route('/collection/{id}', name: 'api_my_collection_show',methods: ['GET'])]
    public function show(MyCollection $myCollection): Response
    {
        // check if $myCollection doesn't exist
        if (!$myCollection) {
            return $this->json(
                "Error : Collection inexistante",
                // status code
                404
            );
        }
        // return json
        return $this->json(
            // what I want to show
            $myCollection,
            // status code
            200,
            // header
            [],
            // groups authorized
            ['groups' => 'get_collection']
            );
    } 
    
    /**
    * create one collection 
    *
    * @param MyCollectionRepository $myCollectionRepository
    * @return Response
    */
   #[Route('/secure/collection', name: 'api_my_collection_create',methods: ['POST'])]
   public function create(Request $request, EntityManagerInterface $entityManager, SerializerInterface $serializer, ValidatorInterface $validator)
   {

    $updateMyCollection = $serializer->deserialize($request->getContent(), MyCollection::class, 'json');

    $myCollection = new MyCollection();

    $myCollection->setUser($this->getUser());
    $myCollection->setName($updateMyCollection->getName());
    $myCollection->setDescription($updateMyCollection->getDescription());
    $myCollection->setImage($updateMyCollection->getImage());
    $myCollection->setUpdatedAt(New DateTimeImmutable());
    $myCollection->setIsActive($updateMyCollection->isIsActive());

    $violations = $validator->validate($myCollection);

    if (0 !== count($violations)) {
        return $this->json([$violations,500,['message' => 'error']]); ;
    } else{
        
        $entityManager->persist($myCollection);
        $entityManager->flush();

        return $this->json($serializer->serialize($myCollection, 'json', ['groups' => 'collection']), 201, ['message' => 'create successful']);
   }
}

    /**
    * update one collection
    *
    * @param MyCollectionRepository $myCollectionRepository
    * @return Response
    */
    #[Route('/secure/collection/{id}', name: 'api_my_collection_update',methods: ['PUT'])]

    public function update(MyCollection $myCollection = null, EntityManagerInterface $entityManager , SerializerInterface $serializer, Request $request,MyObjectRepository $myObjectRepository, ValidatorInterface $validator): Response
    {
        
        // check if $myCollection doesn't exist
        if (!$myCollection) {
            return $this->json(
                "Error : Collection inexistante",
                // status code
                404
            );
        }
        // retrieve data from request
        $jsonData = json_decode($request->getContent(), true);
        // deserialize data
        $updateMyCollection = $serializer->deserialize($request->getContent(), MyCollection::class, 'json');
        // retrieve related objects
        $myObjectId = $jsonData['relatedObjects'];

        $myCollection->setUser($this->getUser());
        $myCollection->setName($updateMyCollection->getName());
        $myCollection->setDescription($updateMyCollection->getDescription());
        $myCollection->setImage($updateMyCollection->getImage());
        $myCollection->setUpdatedAt(New DateTimeImmutable());
        $myCollection->setIsActive($updateMyCollection->isIsActive());
        foreach ($myObjectId as $object) {
            $objectId = $object['id'];
            $objectToRemove = $myObjectRepository->find($objectId);
            if ($objectToRemove) {
                $myCollection->removeMyobject($objectToRemove);
            }
        }

        $violations = $validator->validate($myCollection);
        // if there is an error
        if (0 !== count($violations)) {
            return $this->json([$violations,500,['message' => 'error']]); ;
        } else {    
                $entityManager->flush();
                return $this->json($serializer->serialize($myCollection, 'json', ['groups' => 'collection']), 200, ['message' => 'update successful']);
            }
    }

    /**
    * delete one collection
    * 
    * @param MyCollectionRepository $myCollectionRepository
    * @return Response
    */
    #[Route('/secure/collection/{id}', name: 'api_my_collection_delete', methods: ['DELETE'])]
    public function delete(MyCollection $myCollection, EntityManagerInterface $manager): Response
    {
         // check if $myCollection doesn't exist
        if (!$myCollection) {
            return $this->json(
                ['message' => 'collection inexistant'],
                404,
                );
        }

        $manager->remove($myCollection);
        $manager->flush();

        return $this->json(['message' => 'delete successful', 200]);
       
    }

    /**
     * @Route("/uploadFile", name="upload", methods={"POST"})
     */
    #[Route('/secure/collection/upload_file', name: 'api_collection_upload_file', methods: ['POST'])]
    public function upload(Request $request, MyCollectionRepository $myCollectionRepository, ParameterBagInterface $params, MyCollection $myCollection,EntityManagerInterface $manager)
    {
        // for test only in the back side
         $myCollection = $myCollectionRepository->find(2);

        $image = $request->files->get('file');

        $validator = Validation::createValidator();
        $violations = $validator->validate($image);

        if (0 !== count($violations)) {
            return $this->json([$violations,500,['message' => 'error']]); ;
        } else{
           
            // on ajoute uniqid() afin de ne pas avoir 2 fichiers avec le même nom
            $newFilename = uniqid().'.'. $image->getClientOriginalName();

             // enregistrement de l'image dans le dossier public du serveur
            // paramas->get('public') =>  va chercher dans services.yaml la variable public
            $image->move($params->get('images_collections'), $newFilename);

            // ne pas oublier d'ajouter l'url de l'image dans l'entitée aproprié
            // $entity est l'entity qui doit recevoir votre image
            $myCollection->setImage($newFilename);

            $manager->flush();

            return $this->json([
                'message' => 'Image uploaded successfully.'
            ]);
        }
    } 
    #[Route('/collection_random', name: 'api_my_collection_random',methods: ['GET'])]
    public function random(MyCollectionRepository $myCollectionRepository): Response
    {
        // retrieve all collections
        $collections = $myCollectionRepository->findRandomCollectionSql();
        
        // check if $myCollection doesn't exist
        if (!$collections) {
            return $this->json(
                "Error : Collection inexistante",
                // status code
                404
            );
        }

        // return json
        return $this->json(
            // what I want to show
            $collections,
            // status code
            200,
            // header
            [],
            // groups authorized
            ['groups' => 'get_collection_random']
        );
    }
    #[Route('/secure/add/{id}/favorite', name: 'api_add_collection_favorite',methods: ['POST'])]
    public function newFavorite(MyCollection $myCollection = null, EntityManagerInterface $entityManager,): Response
    {
        // check if $myCollection doesn't exist
        if (!$myCollection) {
            return $this->json(
                "Error : Collection inexistante",
                // status code
                404
            );
        }
        // add user to collection favorite
        $myCollection->addUser($this->getUser());

        $entityManager->persist($myCollection);
        $entityManager->flush();

        // return json
        return $this->json(
            // what I want to show
            $myCollection,
            // status code
            200,
            // header
            [],
            // groups authorized
            ['groups' => 'get_favorite'],

src/Controller/Back/MainController.php
<?php

namespace App\Controller\Back;

use App\Repository\CategoryRepository;
use App\Repository\CommentRepository;
use App\Repository\MyCollectionRepository;
use App\Repository\MyObjectRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    #[Route('/back/main', name: 'app_back_main')]
    public function index(UserRepository $userRepository, MyCollectionRepository $myCollectionRepository, MyObjectRepository $myObjectRepository, CommentRepository $commentRepository , CategoryRepository $categoryRepository): Response
    {
        $usersLimit = $userRepository->findAllLimit5();
        $myCollectionsLimit = $myCollectionRepository->findAllLimit5();
        $myObjectsLimit = $myObjectRepository->findAllLimit5();
        $commentsLimit = $commentRepository->findAllLimit5();
        $categoriesLimit = $categoryRepository->findAllLimit5();

        return $this->render('back/main/index.html.twig', [
            'myCollectionsLimit' => $myCollectionsLimit,
            'myObjectsLimit'=> $myObjectsLimit,
            'commentsLimit' => $commentsLimit,
            'categoriesLimit' => $categoriesLimit,
            'usersLimit' => $usersLimit,
        ]);
    }
}

templates/back/my_collection/_delete_form.html.twig
<div class="table table-hover mt-4">
<form method="post" action="{{ path('app_back_my_collection_delete', {'id': my_collection.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ my_collection.id) }}">
    <button class=" btn btn-danger">Delete</button>
</form>
</div>

templates/back/my_collection/_form.html.twig
<div class="table table-hover mt-4">
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}
</div>

templates/back/my_collection/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit MyCollection{% endblock %}

{% block body %}
<div class="container my-4">
    <h1>Edit MyCollection</h1>

      <a href="{{ path('app_back_my_collection_index') }}"class="btn btn-outline-primary float-end">back to list</a>

    {{ include('back/my_collection/_form.html.twig', {'button_label': 'Update'}) }}

    {{ include('back/my_collection/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/back/my_collection/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}MyCollection index{% endblock %}

{% block body %}
<div class="container my-4">
    <h1>MyCollection index</h1>

    <a href="{{ path('app_back_my_collection_new') }}"class="btn btn-success float-end">Create new</a>

    <table class="table table-hover mt-4">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Image</th>
                <th>Description</th>
                <th>Is_active</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for my_collection in my_collections %}
            <tr>
                <td>{{ my_collection.id }}</td>
                <td>{{ my_collection.name }}</td>
                <td>{{ my_collection.image }}</td>
                <td>{{ my_collection.description|slice(0, 50) }}... </td>
                <td>{{ my_collection.isActive ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_back_my_collection_show', {'id': my_collection.id}) }}"class="btn btn-sm btn-info">show</a>
                    <a href="{{ path('app_back_my_collection_edit', {'id': my_collection.id}) }}"class="btn btn-sm btn-warning">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/back/my_collection/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New MyCollection{% endblock %}

{% block body %}
<div class="container my-4">
    <h1>Create new MyCollection</h1>

    <a href="{{ path('app_back_my_collection_index') }}"class="btn btn-outline-primary float-end">back to list</a>

    {{ include('back/my_collection/_form.html.twig') }}
</div>
    
{% endblock %}

templates/back/my_collection/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}MyCollection{% endblock %}

{% block body %}
<div class="container my-4">
    <h1>MyCollection</h1>

    <a href="{{ path('app_back_my_collection_index') }}"class="btn btn-outline-primary float-end">back to list</a>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ my_collection.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ my_collection.name }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ my_collection.image }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ my_collection.description }}</td>
            </tr>
            <tr>
                <th>Rating</th>
                <td>{{ my_collection.rating }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ my_collection.createdAt ? my_collection.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ my_collection.updatedAt ? my_collection.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Is_active</th>
                <td>{{ my_collection.isActive ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>


    <a href="{{ path('app_back_my_collection_edit', {'id': my_collection.id}) }}"class="btn btn-warning">edit</a>


    {{ include('back/my_collection/_delete_form.html.twig') }}
</div>
{% endblock %}